version: '3'

services:
  java-app:
    image: spring-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - SERVER_PORT= 8080


  database:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    container_name: database
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
        postgres -c max_connections=1000
                 -c shared_buffers=256MB
                 -c effective_cache_size=768MB
                 -c maintenance_work_mem=64MB
                 -c checkpoint_completion_target=0.7
                 -c wal_buffers=16MB
                 -c default_statistics_target=100
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
        interval: 30s
        timeout: 10s
        retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true

volumes:
  pgdata:
    driver: local