- name: dockerhub login
  community.docker.docker_login:
    username: "{{ dockerhub_username }}"
    password: "{{ dockerhub_password }}"

- name: docker-compose up -d
  command: docker compose up -d
  args:
    chdir: "{{ project_dir }}"

- name: push
  shell: |
    docker compose build
    docker compose push
  args:
    chdir: "{{ project_dir }}"