apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kube-state-metrics
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8082
      targetPort: 8080
      nodePort: 30882
  selector:
    app.kubernetes.io/name: kube-state-metrics
