apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: kube-system
  labels:
    app.kubernetes.io/name: prometheus-node-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-node-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus-node-exporter
    spec:
      containers:
        - name: node-exporter
          image: prom/node-exporter:v1.6.1
          args:
            - "--path.rootfs=/host"
          ports:
            - containerPort: 9100
          volumeMounts:
            - name: root
              mountPath: /mnt/data/metric
              readOnly: true
      volumes:
        - name: root
          hostPath:
            path: /mnt/data/metric