apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: kube-system
  labels:
    app.kubernetes.io/name: prometheus-node-exporter
spec:
  type: NodePort
  ports:
    - port: 9100
      targetPort: 9100
      nodePort: 30100
  selector:
    app.kubernetes.io/name: prometheus-node-exporter