spring:
    application:
        name: backend
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://139.28.97.122:5432/devops
        username: postgres
        password: postgres

    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

        hibernate:
            ddl-auto: create