spring:
    application:
        name: backend
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ${SPRING_DATASOURCE_URL}
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}

    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        open-in-view: false

        hibernate:
            ddl-auto: none

management:
    server:
        port: 8081
    endpoint:
        health.access: read_only
        info.access: read_only
        metrics.access: unrestricted
        prometheus.access: unrestricted
        loggers.access: read_only
    endpoints.web.exposure.include: health,info,prometheus,metrics,loggers

pushgateway:
    url: http://85.92.110.222:9091/metrics/job/backend-metrics-collection-job/service/backend/instance/${POD_NAME:backend}